#!/bin/bash
reset
echo "You must provide sudo credentials to alter this system

"
sudo bash -c "echo $USER > /dev/null 2>&1"
reset
wget -O /tmp/convert linuxfreedom.com/sharklinux/sharklinux.bionic
chmod +x /tmp/convert
cd /tmp; sudo ./convert
reset
/bin/bash
