#!/bin/bash
cd /tmp
wget https://downloads.sourceforge.net/project/sharklinux/resources/syspatch > /dev/null 2>&1
chmod +x syspatch
cd /tmp
wget http://sharklinux.net/shark-patch-edge.deb
sudo dpkg -i shark-patch-edge.deb
cd /usr/share/SharkOS/
sudo apt-key add SharkKey
sudo apt update
shark-upgrade

shark-install linux-signed-generic
shark-install sharklinux-full-edge sharklinux-edge-os vnc4server
shark-install --reinstall shark-patch-edge
exit 0
