#!/bin/bash
cd /tmp
wget https://downloads.sourceforge.net/project/sharklinux/resources/syspatch > /dev/null 2>&1
wget http://sharklinux.net/shark-patch.deb
sudo dpkg -i shark-patch.deb
sudo apt update
sudo apt -y install pkgmr
pkg upgrade
. ~/.bashrc
sudo reboot
exit 0
