#!/bin/bash
cd /tmp
wget https://downloads.sourceforge.net/project/sharklinux/bootstrap/sharkstrap > /dev/null 2>&1
chmod +x sharkstrap
sudo ./sharkstrap base
sudo rm /usr/bin/sharkstrap
sudo reboot
exit 0
