#!/bin/bash
cd /tmp
wget -t 5 -T 5 -E https://downloads.sourceforge.net/project/sharklinux/bootstrap/sharkstrap
ls sharkstrap || wget sharklinux.net/sharkstrap
chmod +x sharkstrap
sudo ./sharkstrap base
sudo dpkg -i shark-patch.deb
sudo reboot
exit 0
