#!/bin/bash
wget sharklinux.net/sharkbase -O- | sh
sudo bash -c "sed -i -e 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config"
sudo bash -c "service ssh restart"
sudo bash -c "userdel -r ubuntu"
sudo bash -c "echo np | adduser marcus"
sudo bash -c 'echo "marcus:Kristen" | chpasswd'
sudo bash -c "adduser marcus sudo"
pkg install sharklinux-full  xrdp
sudo chmod 777 /var/run/libvirt/libvirt-sock
sudo adduser $USER libvirtd
sudo chown $USER  /var/run/libvirt/libvirt-sock
sudo bash -c "echo 'wget sharklinux.net/iso -O- | sh' > /usr/local/bin/buildiso; chmod +x /usr/local/bin/buildiso"
pkg purge 4.13.0*
pkg install linux-virtual
sudo reboot

