#!/bin/bash
wget sharklinux.net/sharkbase -O- | sh
pkg install xfce4 mate-terminal caja pluma google-chrome* deluge
echo "pkg install nordvpn-sl; nordvpn; nordvpn connect" > /usr/bin/subsysvpn
chmod 777 /usr/bin/subsysvpn
shark-guac
reboot
