#!/bin/bash
cd /tmp
wget -O /tmp/start.deb sharklinux.net/focal.deb; sudo dpkg -i /tmp/start.deb; sudo apt update; sudo apt -y install -f
pkg refresh

rm start.deb
echo "SharkLinux" > /etc/hostname
echo "SharkLinux" >> /etc/hosts
sudo usermod -u 499 libvirt-qemu    
find / -user $(id -u libvirt-qemu) -exec chown -h 499 {} \; > /dev/null 2>&1
sudo ex +"%s@DPkg@//DPkg" -cwq /etc/apt/apt.conf.d/70debconf > /dev/null 2>&1
sudo dpkg-reconfigure debconf -f noninteractive -p critical > /dev/null 2>&1
sudo debconf-apt-progress --start 
sudo debconf-apt-progress -- apt -y update

sudo debconf-apt-progress -- apt -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
sudo debconf-apt-progress -- apt -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install  screenie mate-desktop-environment-extras variety gimp thunderbird google-chrome-stable dropbox synaptic vlc x11vnc filezilla xvfb obsidian-icon-theme adapta-gtk-theme sharklinux-lxdgui sharklinux-multipass sharklinux-default-settings virt-manager qemu-kvm qemu libreoffice gigolo sharkdm
sudo reboot
exit 0



