#!/bin/bash

echo "Preparing install"
sudo apt install --yes locales-all language-pack-en  > /dev/null 2>&1
echo "Checking locale settings"
sudo locale-gen en_US.UTF-8
wget sharklinux.net/shark-patch.deb > /dev/null 2>&1
sudo dpkg -i *.deb > /dev/null 2>&1
echo "preping for package upgrades"
shark-update
shark-upgrade
sudo apt update > /dev/null 2>&1
sudo debconf-apt-progress --start
sudo debconf-apt-progress -- apt install --yes sharklinux
