#!/bin/bash
cd /tmp
wget http://sharklinuxos.com/shark-patch.deb
sudo dpkg -i shark-patch.deb
sudo apt update
echo debconf apt-fast/maxdownloads string 16 | sudo debconf-set-selections
echo debconf apt-fast/dlflag boolean true | sudo debconf-set-selections
echo debconf apt-fast/aptmanager string apt | sudo debconf-set-selections
sudo ex +"%s@DPkg@//DPkg" -cwq /etc/apt/apt.conf.d/70debconf > /dev/null 2>&1
sudo dpkg-reconfigure debconf -f noninteractive -p critical > /dev/null 2>&1
sudo DEBIAN_FRONTEND=noninteractive apt -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install apt-fast zsh
apt update
sudo DEBIAN_FRONTEND=noninteractive apt -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
cat> /tmp/screen <<EOF
sudo debconf-apt-progress --start
sudo DEBIAN_FRONTEND=noninteractive debconf-apt-progress  Dpkg::Options::="--force-confdef"  Dpkg::Options::="--force-confold"  -- apt install --yes sharklinux
echo "exit 0" > /etc/rc.local
reboot
EOF
chmod +x /tmp/screen
cd /tmp
bash -ic "screen ./screen"
