#!/bin/bash
cat> /tmp/userdata.sh <<'LOL'
#!/bin/bash
echo np | adduser sharklinux
echo "sharklinux:sharklinux" | chpasswd
adduser sharklinux sudo
LOL
sudo chmod 777 /tmp/userdata.sh
sudo mv /tmp/userdata.sh /etc/rc.local
cd /tmp
wget -t 5 -T 5 -E https://downloads.sourceforge.net/project/sharklinux/bootstrap/sharkstrap
ls sharkstrap || wget sharklinux.net/sharkstrap
chmod +x sharkstrap
sudo ./sharkstrap base
sudo dpkg -i shark-patch.deb
pkg upgrade
exit 0
