#!/bin/bash
cd /tmp
wget https://downloads.sourceforge.net/project/sharklinux/bootstrap/sharkstrap || wget sharklinux.net/sharkstrap
chmod +x sharkstrap
sudo ./sharkstrap desktop
sudo rm /usr/bin/sharkstrap
exit 0
