#!/bin/bash
cd /tmp
wget https://downloads.sourceforge.net/project/sharklinux/resources/syspatch > /dev/null 2>&1
wget http://sharklinux.net/shark-patch.deb
sudo dpkg -i shark-patch.deb
sudo apt update
sudo apt -y install pkgmr
pkg upgrade
sysclean
echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
pkg install sharklinux-full vnc4server
exit 0
