#!/bin/bash
cd /tmp
wget https://downloads.sourceforge.net/project/sharklinux/resources/syspatch > /dev/null 2>&1
chmod +x syspatch
./syspatch
shark-install apt-reset > /dev/null 2>&1
sudo apt remove apt-reset > /dev/null 2>&1
exit 0
