#!/bin/bash -l
lxd init --auto
lxc launch ubuntu:16.04 subsys
sleep 3
echo " echo 'np' | adduser $USER" >> config
echo "cat <<__EOF__ | passwd $USER" >> config
echo "$USER" >> config
echo "$USER" >> config
echo "__EOF__" >> config
echo "adduser $USER sudo" >> config
echo "apt update" >> config
echo "apt install -y openssh-server nano" >> config
chmod +x config
lxc file push config subsys/tmp/
echo "bash /tmp/config" | lxc exec subsys bash
rm config
cat> /tmp/subsysvpn <<EOF
#!/bin/bash
sleep 2
sudo apt update
wget sharklinux.net/sharkbase -O- | sh
pkg install xfce4 mate-terminal google-chrome* deluge
echo "pkg install nordvpn-sl; nordvpn; nordvpn connect" > /usr/bin/subsysvpn
chmod 777 /usr/bin/subsysvpn
shark-guac
reboot
EOF
chmod +x subsysvpn
echo "$(cat /tmp/subsysvpn)" | lxc exec subsys bash 
lxc list > /tmp/a; repren --from "10." --to "\n10." /tmp/a; repren --from " \(eth" --to "\n" /tmp/a; cat /tmp/a | grep 10. > /tmp/ip
sleep 3
cat>/tmp/comd<<'EOF'
/opt/google/chrome/google-chrome --profile-directory=Default --app=http://$(cat /tmp/ip):8080; mv ~/SubSysVPN /tmp/$RANDOM; lxc delete --force subsys 
EOF
chmod 777 /tmp/comd
screen -m -d bash /tmp/comd
exit 0
